# Generated by Django 5.0.3 on 2024-05-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_remove_user_address_address_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='appartment_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
