# Generated by Django 5.0.3 on 2024-05-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_alter_address_appartment_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='appartment_no',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
