# Generated by Django 5.0.3 on 2024-05-22 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_car_category_alter_address_appartment_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Adres', 'verbose_name_plural': 'Adresy'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Samochód', 'verbose_name_plural': 'Samochody'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Wyposażenie', 'verbose_name_plural': 'Wyposażenia'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Zamówienie', 'verbose_name_plural': 'Zamówienia'},
        ),
        migrations.AlterField(
            model_name='address',
            name='appartment_no',
            field=models.CharField(blank=True, default='', help_text='To pole jest opcjonalne.', max_length=10, verbose_name='Numer mieszkania'),
        ),
        migrations.AlterField(
            model_name='address',
            name='building_no',
            field=models.CharField(max_length=10, verbose_name='Numer budynku'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=30, verbose_name='Kraj'),
        ),
        migrations.AlterField(
            model_name='address',
            name='post_code',
            field=models.CharField(max_length=10, verbose_name='Kod pocztowy'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=50, verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='użytkownik'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment',
            field=models.CharField(max_length=50, verbose_name='Wyposażenie'),
        ),
        migrations.AlterField(
            model_name='order',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='rental.car', verbose_name='Samochód'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='rental.user', verbose_name='Klient'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deposit',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Depozyt'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Wartość zamówienia'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('karta', 'Karta'), ('gotowka', 'Gotówka'), ('przelew', 'Przelew'), ('blik', 'Blik')], max_length=20, verbose_name='Metoda płatności'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.BooleanField(verbose_name='Status płatoności'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_date',
            field=models.DateTimeField(verbose_name='Data odebrania'),
        ),
        migrations.AlterField(
            model_name='order',
            name='return_date',
            field=models.DateTimeField(verbose_name='Data zwrotu'),
        ),
        migrations.AlterField(
            model_name='user',
            name='identity_document_no',
            field=models.CharField(max_length=20, verbose_name='Numer dokumentu tożasamości'),
        ),
        migrations.AlterField(
            model_name='user',
            name='identity_document_type',
            field=models.CharField(choices=[('dowod', 'Dowód osobisty'), ('passport', 'Paszport'), ('prawo_jazdy', 'Prawo jazdy')], max_length=20, verbose_name='Typ dokumentu tożasamości'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Numer telefonu'),
        ),
    ]
