# Generated by Django 5.0.3 on 2024-05-22 15:08

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rental', '0006_alter_address_options_alter_car_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=20, verbose_name='Numer telefonu')),
                ('identity_document_no', models.CharField(max_length=20, verbose_name='Numer dokumentu tożsamości')),
                ('identity_document_type', models.CharField(choices=[('dowod', 'Dowód osobisty'), ('passport', 'Paszport'), ('prawo_jazdy', 'Prawo jazdy')], max_length=20, verbose_name='Typ dokumentu tożsamości')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Klient'),
        ),
        migrations.AlterField(
            model_name='order',
            name='declared_order_duration',
            field=models.DurationField(verbose_name='Deklarowany czas wypożyczenia'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.BooleanField(verbose_name='Status płatności'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
