# Generated by Django 5.0.3 on 2024-05-22 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_rentaluser'),
        ('rental', '0008_alter_address_user_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.rentaluser', verbose_name='użytkownik'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auth.rentaluser', verbose_name='Klient'),
        ),
        migrations.DeleteModel(
            name='RentalUser',
        ),
    ]
