# Generated by Django 5.0.3 on 2024-05-22 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_alter_address_user_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='gearbox_types',
            new_name='gearbox_type',
        ),
    ]
