# Generated by Django 5.0.3 on 2024-05-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_rename_gearbox_types_car_gearbox_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='gearbox_type',
            field=models.CharField(choices=[('automatyczna', 'Automatyczna'), ('manualna', 'Manualna'), ('pol_automatyczna', 'Pół automatyczna')], max_length=20, verbose_name='Typ skrzyni biegów'),
        ),
    ]
