# Generated by Django 5.0.3 on 2024-05-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0012_alter_address_options_alter_car_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('suv', 'SUV'), ('city-friendly', 'City-friendly'), ('off-road', 'Off-road'), ('van', 'Van'), ('sports', 'Sports')], max_length=50, verbose_name='Category'),
        ),
    ]
