# Generated by Django 5.0.3 on 2024-06-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0013_alter_car_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='declared_order_duration',
            field=models.IntegerField(verbose_name='Declared rental duration'),
        ),
    ]
