# Generated by Django 5.0.3 on 2024-06-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0015_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='images'),
        ),
    ]
