# Generated by Django 5.0.3 on 2024-06-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0018_alter_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default='images/default_image.jpg', upload_to='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.BooleanField(default=False, verbose_name='Payment status'),
        ),
    ]
