# Generated by Django 6.0.2 on 2026-02-16 10:46

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipment",
                    models.CharField(max_length=50, verbose_name="Equipment"),
                ),
            ],
            options={
                "verbose_name": "Equipment",
                "verbose_name_plural": "Equipments",
            },
        ),
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Phone number")),
                (
                    "identity_document_no",
                    models.CharField(
                        max_length=20, verbose_name="Identity document number"
                    ),
                ),
                (
                    "identity_document_type",
                    models.CharField(
                        choices=[
                            ("identity_card", "Identity card"),
                            ("passport", "Passport"),
                            ("driver_license", "Driver's license"),
                        ],
                        max_length=20,
                        verbose_name="Identity document type",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User data",
                "verbose_name_plural": "User data (Rental)",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=30, verbose_name="Country")),
                ("city", models.CharField(max_length=30, verbose_name="City")),
                (
                    "post_code",
                    models.CharField(max_length=10, verbose_name="Post code"),
                ),
                ("street", models.CharField(max_length=50, verbose_name="Street")),
                (
                    "building_no",
                    models.CharField(max_length=10, verbose_name="Building number"),
                ),
                (
                    "appartment_no",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="This field is optional.",
                        max_length=10,
                        verbose_name="Apartment number",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("suv", "SUV"),
                            ("city-friendly", "City-friendly"),
                            ("off-road", "Off-road"),
                            ("van", "Van"),
                            ("sports", "Sports"),
                        ],
                        max_length=50,
                        verbose_name="Category",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="images/default_image.jpg",
                        upload_to="images",
                        verbose_name="Image",
                    ),
                ),
                ("brand", models.CharField(max_length=50, verbose_name="Brand")),
                ("model", models.CharField(max_length=50, verbose_name="Model")),
                (
                    "engine_type",
                    models.CharField(
                        choices=[
                            ("petrol", "Petrol"),
                            ("diesel", "Diesel"),
                            ("hybrid", "Hybrid"),
                            ("electric", "Electric"),
                            ("hydrogen", "Hydrogen"),
                        ],
                        max_length=20,
                        verbose_name="Engine type",
                    ),
                ),
                (
                    "seats_count",
                    models.PositiveBigIntegerField(verbose_name="Number of seats"),
                ),
                (
                    "doors_count",
                    models.PositiveSmallIntegerField(verbose_name="Number of doors"),
                ),
                ("fuel_usage", models.FloatField(verbose_name="Fuel consumption")),
                (
                    "engine_power",
                    models.PositiveSmallIntegerField(verbose_name="Engine power"),
                ),
                ("color", models.CharField(max_length=20, verbose_name="Color")),
                (
                    "gearbox_type",
                    models.CharField(
                        choices=[
                            ("automatic", "Automatic"),
                            ("manual", "Manual"),
                            ("semi-automatic", "Semi-automatic"),
                        ],
                        max_length=20,
                        verbose_name="Gearbox type",
                    ),
                ),
                ("available", models.BooleanField(verbose_name="Availability")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Value"
                    ),
                ),
                (
                    "equipment",
                    models.ManyToManyField(
                        to="rental_app.equipment", verbose_name="Equipment"
                    ),
                ),
            ],
            options={
                "verbose_name": "Car",
                "verbose_name_plural": "Cars",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Order value"
                    ),
                ),
                (
                    "declared_order_duration",
                    models.IntegerField(
                        null=True, verbose_name="Declared rental duration"
                    ),
                ),
                ("pickup_date", models.DateTimeField(verbose_name="Pickup date")),
                ("return_date", models.DateTimeField(verbose_name="Return date")),
                (
                    "deposit",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Deposit"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("card", "Card"),
                            ("cash", "Cash"),
                            ("transfer", "Transfer"),
                            ("blik", "Blik"),
                        ],
                        max_length=20,
                        verbose_name="Payment method",
                    ),
                ),
                (
                    "payment_status",
                    models.BooleanField(default=False, verbose_name="Payment status"),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="rental_app.car",
                        verbose_name="Car",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
    ]
